name: Deploy Express to OCI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: dockeradmin
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/dockeradmin/git-actions
            git pull
            docker-compose up -d --build